name: Test S3 Sync Metadata with OIDC

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::645508719107:role/actiontestingusingoidc
          aws-region: ap-south-1
      
      - name: Create test HTML file
        run: |
          mkdir -p test
          echo "<html><body><h1>Test HTML File</h1></body></html>" > test/index
          echo "<html><body><h1>Test HTML File with Extension</h1></body></html>" > test/index.html
      
      - name: Test S3 Sync Metadata Action
        uses: ./
        with:
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
          source_dir: ./test
          args: --delete
